# Ex2 - Getting and Knowing your Data

This time we are going to pull data directly from the internet.
Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

### Step 1. Import the necessary libraries

In [1]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv).

### Step 3. Assign it to a variable called chipo.

In [2]:
chipo = pd.read_csv("https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv", sep="\t", header=0)

### Step 4. See the first 10 entries

In [6]:
chipo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            4622 non-null   int64
 1   quantity            4622 non-null   int64
 2   item_name           4622 non-null   object
 3   choice_description  3376 non-null   object
 4   item_price          4622 non-null   object
dtypes: int64(2), object(3)
memory usage: 180.7+ KB

### Step 5. What is the number of observations in the dataset?

In [7]:
# Solution 1
len(chipo)

4622

In [8]:
# Solution 2

chipo.shape[0]

4622

### Step 6. What is the number of columns in the dataset?

In [11]:
chipo.shape

(4622, 5)

### Step 7. Print the name of all the columns.

In [13]:
chipo.columns

Index(['order_id', 'quantity', 'item_name', 'choice_description',
       'item_price'],
      dtype='object')

### Step 8. How is the dataset indexed?

In [42]:
chipo.index

RangeIndex(start=0, stop=4622, step=1)

### Step 9. Which was the most-ordered item?

In [44]:
c = chipo.groupby(['item_name'])
c.sum().sort_values(by='quantity', ascending=False).head(1)

'Chips and Fresh Tomato Salsa'

### Step 10. For the most-ordered item, how many items were ordered?

In [58]:
c = chipo.groupby(['item_name'])
c.sum().sort_values(by='quantity', ascending=False).head(1)

              order_id  quantity
item_name
Chicken Bowl    713926       761

### Step 11. What was the most ordered item in the choice_description column?

In [75]:
c=chipo.groupby('choice_description')
c.sum().sort_values(by='quantity', ascending=False)

                                                    order_id  quantity
choice_description
[Diet Coke]                                           123455       159
[Coke]                                                122752       143
[Sprite]                                               80426        89
[Fresh Tomato Salsa, [Rice, Black Beans, Cheese...     43088        49
[Fresh Tomato Salsa, [Rice, Black Beans, Cheese...     36041        42
...                                                      ...       ...
[Roasted Chili Corn Salsa, [Fajita Vegetables, ...       577         1
[Roasted Chili Corn Salsa, [Fajita Vegetables, ...       585         1
[Roasted Chili Corn Salsa, [Fajita Vegetables, ...       235         1
[Roasted Chili Corn Salsa, [Guacamole, Sour Cre...       987         1
[[Tomatillo-Red Chili Salsa (Hot), Tomatillo-Gr...      1299         1

[1043 rows x 2 columns]

### Step 12. How many items were orderd in total?

In [5]:
chipo['item_price'].str[0]

0       $
1       $
2       $
3       $
4       $
       ..
4617    $
4618    $
4619    $
4620    $
4621    $
Name: item_price, Length: 4622, dtype: object

### Step 13. Turn the item price into a float

#### Step 13.a. Check the item price type

In [102]:
chipo['item_price_f'] = pd.to_numeric(chipo['item_price'].str[1:], downcast='float')
chipo['item_price_f'].dtypes

dtype('float32')

#### Step 13.b. Create a lambda function and change the type of item price

In [9]:
item_price_f = lambda x: float(x[1:])
chipo['item_price_f'] = chipo.item_price.apply(item_price_f)

dtype('float64')

#### Step 13.c. Check the item price type

In [10]:
chipo.item_price_f.dtype

dtype('float64')

### Step 14. How much was the revenue for the period in the dataset?

In [16]:
(chipo.item_price_f * chipo.quantity).sum()

39237.02

### Step 15. How many orders were made in the period?

In [21]:
chipo.order_id.value_counts().count()

1834

### Step 16. What is the average revenue amount per order?

In [29]:
# Solution 1

chipo['revenue'] = chipo.item_price_f * chipo.quantity

g = chipo.groupby('order_id')
g.sum().revenue.mean()

21.39423118865867

In [ ]:
# Solution 2

### Step 17. How many different items are sold?

In [35]:
chipo.item_name.value_counts().count()

50